### ISSUE TITLE
Gstreamer discussion

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#6]
On Wed, May 20, 2015 at 4:29 PM, Liuting Du <liuting@evercam.io> wrote:
Are you saying that instead of passing the full pipeline string, we should link the elements manually by writing the C code?

But because currently the demo app works quite well on our phones, we can change it only if the performance is better, or more features can be done in that way.. Forgot to mention that I've created the issues list: https://github.com/evercam/evercam-play-android/issues

I did check the Github project when I started learning GStreamer, the C part was just too complicated for me.. So I went to another approach..

As I can see from the code, it is using rtspsrc as well:

static void
204	need_data_cb (GstElement *playbin, GstElement *rtspsrc, gpointer user_data)
…	
213	  g_object_set (G_OBJECT (rtspsrc), "user-id", priv->user, NULL);
214	  g_object_set (G_OBJECT (rtspsrc), "user-pw", priv->pass, NULL);

So it seems like the element - rtspsrc is the right one to use, right?

I don't really understand what is the 'rtsplib', is it the very low level methods for RTSP streaming? 

Please correct me if I am wrong about anything.

Thank you for the patience and don't worry about the English:)

On Wed, May 20, 2015 at 4:06 PM, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
I mean something like this, here is video

2015-05-20 16:55 GMT+03:00 Dmitry Adjiev <adjiev.dmitry@gmail.com>:
Guys, I'm bad teacher and also my english is not better :-)
So please feel free to ask me, I'll explain every thing what I really know

2015-05-20 16:55 GMT+03:00 Dmitry Adjiev <adjiev.dmitry@gmail.com>:
I'll test Evercam app one more time, but little later, currently i going in a meeting.
Sorry, I should explain you:

W/linker  ( 2863): libgstreamer_android.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
W/VideoCapabilities( 2863): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities( 2863): Unsupported profile 4 for video/mp4v-es
W/VideoCapabilities( 2863): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities( 2863): Unsupported profile 4 for video/mp4v-es
I/GStreamer( 2863): GStreamer initialization complete

Here is no message about crash (as you can see), I can't see video because your hardcoded rtspsrc caps doesn't correspond to video stream caps.
But in office it doesn't work too, seems it's proxy issue, we use proxy here.
Why caps are different if we try to play the same stream?
I think first step it's adding good logging to app and I think we can't just do it via pipeline, but we can try to build gst-launch for android, it will good for debugging, or we can use
gstreamer rtsplib and get full control ...

Here is gstreamer reference
http://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/html/

In this case we need to make pipeline manually, but we need it anyway if some plugins doesn't work ... also we need to understand what happends with jpegenc ..

Do video caps depend from network speed or something else?
Can we check it on server side?
What do you think?

2015-05-20 16:08 GMT+03:00 Liuting Du <liuting@evercam.io>:
You can just log in with the Evercam account I created for you: 

Username: dmitry and Password: dmitry

I think I understand what you are talking about, but it's a really weird error because we are using the same phone. Is your phone rooted?

I checked the logcat when it running on my phone, it has the same text relocation warning, but it's just a warning message without crashing the app, the video is successfully played.. Is the app crashing on your phone? What error message is showing in the app UI?

On Wed, May 20, 2015 at 1:25 PM, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
I'm at office now, just short testing
GstreamerDemo.apk can't play video

W/linker  ( 2863): libgstreamer_android.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
W/VideoCapabilities( 2863): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities( 2863): Unsupported profile 4 for video/mp4v-es
W/VideoCapabilities( 2863): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities( 2863): Unsupported profile 4 for video/mp4v-es
I/GStreamer( 2863): GStreamer initialization complete

This is the reason why i use playbin, I'll try to find faster solution.

With EvercamPlayGstreamer.apk i have login error, but may be i did something wrong, I'll test it at home more time

2015-05-20 14:56 GMT+03:00 Liuting Du <liuting@evercam.io>:
Just tested both versions of the demo app on Marco's Moto G - 4.4.4, they both works, your 'playbin' version takes more than 10 seconds to load the stream and the 'rtspsrc' takes less than 5 second.

The video loading speed is very important for us, that's why I used rtspsrc.

Are you using Nexus 5 - Android 5.1, if you do, it should work because I am using exactly the same phone with you. So please install the latest package that I sent and let me know if it works on your device.

Not sure what you mean about 'fixed format', or can you send the pull request so that I can see your code and understand the situation better? Sorry that it's very difficult for me to understand the GStreamer concept and thank you helping me learning:) 

Thanks,
Liuting

On Wed, May 20, 2015 at 12:11 PM, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
Not yet, I suggest to use dynamic caps because when you select some concrete profile it may not work on other devices, as you can see from my logcat output my device doesn't support your profile 4.
This is the reason why I told about fixed format, but if you want I cant try to investigate this ...
Marco, please confirm the app can play video stream on your device, if so we have at least one not better, but anyway working way ...

2015-05-20 13:42 GMT+03:00 Liuting Du <liuting@evercam.io>:
Hi Dmitry,

I see in the log trace you sent: 

05-19 20:44:06.976  13110-13110/com.centricular.androidlaunch I/GStreamer﹕ GStreamer initialization complete
05-19 20:44:06.976  13110-13110/com.centricular.androidlaunch W/System.err﹕ java.io.FileNotFoundException: fontconfig/fonts.conf

The file 'fontconfig/fonts.conf' was created when you successfully run 'ndk-build', can you try compile it with NDK again?

The apks I sent should work for you, let me know if it doesn''t.

Tried your app again and it plays the stream, but I have to wait for ~5 seconds before the stream getting loaded. I thought it didn't work because I didn't wait that long for the last time, sorry :). Did you made it work for taking snapshot? Anything else should I test in the demo you sent?

Thanks,
Liuting

On Wed, May 20, 2015 at 11:24 AM, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
Please find my in line comments
I'll check attached apps when I'll at home.

2015-05-20 11:52 GMT+03:00 Liuting Du <liuting@evercam.io>:
You can send a pull request to commit your code, can't wait to see the changes you've made!

I will create a list of todo items as issues in the Evercam Play project, before that you can see them in this doc: https://github.com/evercam/evercam-play-android/wiki/GStreamer-Work

On Wed, May 20, 2015 at 9:44 AM, Liuting Du <liuting@evercam.io> wrote:
​​Hi Dmitry,

Thank you for working on this and sorry I didn't check your mail yesterday..

Did you get the error when running the .apk I attached, or when you build the project by yourself?
Yes, I sent you logcat output, it could not to find libraries and other gstreamer stuff

Are you using Android Studio? Did you run 'ndk-build' before building the Java code?
Yes, I use android studio and I edited gradle scripts for fixing issues with libraries 

The apk you attached doesn't work for me either...
Please send me logcat output.

I agree to use Github issues, but I think the project we work on together should be Evercam Play - GStreamer branch, because that's the latest integration with our app and that is what we want to make it work. See the 'build' section in this doc: https://github.com/evercam/evercam-play-android/wiki/GStreamer-Work, you should be able to build it and get it running by following it.

Can you please install the apks attached in this Email to confirm are they working or not? One is the demo that using pipeline 'rtspsrc' and the other one is Evercam Play with GStreamer integrated. Marco can you please install them as well?

​
 EvercamPlayGStreamer.apk
​
Thanks,
Liuting

On Tue, May 19, 2015 at 11:41 PM, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
> Thanks a lot!!! :-)
> Yes, I wait for LD feedback, She knows what should she do, it's her project
> :-)
>
> 2015-05-20 1:31 GMT+03:00 Marco Herbst <marco@evercam.io>:
>>
>> Not sure if this is helpful, as I am not 100% clear on what I should see,
>> but for me, I install and I get no stream . I do see a "save" button ,but
>> otherwise nothing useful is going on .... LD will give you more useful
>> feedback I hope.
>>
>> m
>>
>> On 19 May 2015 at 19:09, Dmitry Adjiev <adjiev.dmitry@gmail.com> wrote:
>>>
>>>
>>>
>>> 2015-05-19 20:54 GMT+03:00 Dmitry Adjiev <adjiev.dmitry@gmail.com>:
>>>>
>>>> Your project works too with pipeline
>>>>
>>>> playbin
>>>> uri=rtsp://admin:mehcam@89.101.130.1:9021/h264/ch1/main/av_stream
>>>>
>>>> We need to think. ....
>>>>
>>>> Marco, i think we can start discussion of git issues
>>>>
>>>>
>>>> 2015-05-19 20:46 GMT+03:00 Dmitry Adjiev <adjiev.dmitry@gmail.com>:
>>>>>
>>>>> I got why it crashes, it's my bad
>>>>>
>>>>> 05-19 20:18:02.843  27684-27684/com.centricular.androidlaunch
>>>>> E/AndroidRuntime﹕ FATAL EXCEPTION: main
>>>>>     Process: com.centricular.androidlaunch, PID: 27684
>>>>>     java.lang.UnsatisfiedLinkError:
>>>>> dalvik.system.PathClassLoader[DexPathList[[zip file
>>>>> "/data/app/com.centricular.androidlaunch-1/base.apk"],nativeLibraryDirectories=[/vendor/lib,
>>>>> /system/lib]]] couldn't find "libgstreamer_android.so"
>>>>>             at java.lang.Runtime.loadLibrary(Runtime.java:366)
>>>>>             at java.lang.System.loadLibrary(System.java:988)
>>>>>             at
>>>>> com.centricular.androidlaunch.AndroidLaunch.<clinit>(AndroidLaunch.java:66)
>>>>>             at java.lang.reflect.Constructor.newInstance(Native Method)
>>>>>             at java.lang.Class.newInstance(Class.java:1606)
>>>>>             at
>>>>> android.app.Instrumentation.newActivity(Instrumentation.java:1066)
>>>>>             at
>>>>> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
>>>>>             at
>>>>> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>>>>>             at
>>>>> android.app.ActivityThread.access$800(ActivityThread.java:151)
>>>>>             at
>>>>> android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>>>>>             at android.os.Handler.dispatchMessage(Handler.java:102)
>>>>>             at android.os.Looper.loop(Looper.java:135)
>>>>>             at
>>>>> android.app.ActivityThread.main(ActivityThread.java:5254)
>>>>>             at java.lang.reflect.Method.invoke(Native Method)
>>>>>             at java.lang.reflect.Method.invoke(Method.java:372)
>>>>>             at
>>>>> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>>>>>             at
>>>>> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>>>>>
>>>>>
>>>>> And after fiing issue above i have:
>>>>>
>>>>> 5-19 20:44:06.214  13110-13110/com.centricular.androidlaunch I/art﹕
>>>>> Late-enabling -Xcheck:jni
>>>>> 05-19 20:44:06.276  13110-13110/com.centricular.androidlaunch W/linker﹕
>>>>> libgstreamer_android.so has text relocations. This is wasting memory and
>>>>> prevents security hardening. Please fix.
>>>>> 05-19 20:44:06.535  13110-13110/com.centricular.androidlaunch
>>>>> W/VideoCapabilities﹕ Unrecognized profile 2130706433 for video/avc
>>>>> 05-19 20:44:06.558  13110-13110/com.centricular.androidlaunch
>>>>> I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
>>>>> 05-19 20:44:06.564  13110-13110/com.centricular.androidlaunch
>>>>> W/VideoCapabilities﹕ Unrecognized profile 2130706433 for video/avc
>>>>> 05-19 20:44:06.565  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.275862709 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.566  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.276459792 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.567  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.277134636 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.569  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.279201407 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.572  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.282455365 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.573  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.283136719 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.573  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.283675313 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.574  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.284186459 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.574  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.284736771 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.575  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.285294636 0xa140dda0 gstamc.c:2291:scan_codecs
>>>>> Decoder codec has unknown color formats, ignoring
>>>>> 05-19 20:44:06.576  13110-13110/com.centricular.androidlaunch
>>>>> I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
>>>>> 05-19 20:44:06.581  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.291511771 0xa140dda0
>>>>> gstamc.c:3872:gst_amc_codec_info_to_caps Unsupported mimetype 'audio/opus'
>>>>> 05-19 20:44:06.581  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.291893803 0xa140dda0
>>>>> gstamc.c:3872:gst_amc_codec_info_to_caps Unsupported mimetype 'audio/gsm'
>>>>> 05-19 20:44:06.582  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.292289115 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.582  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.292343334 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.582  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.292933438 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.582  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.292987917 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.583  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.293434896 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.583  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.293488594 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.583  13110-13110/com.centricular.androidlaunch
>>>>> E/GStreamer+amc﹕ 0:00:00.293573750 0xa140dda0
>>>>> gstamc.c:4063:gst_amc_codec_info_to_caps Unable to map H264 profile
>>>>> 0x7f000001
>>>>> 05-19 20:44:06.585  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.295959948 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.586  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.296025573 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.586  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.296371146 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.586  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.296458438 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.588  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.298084427 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.588  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.298179375 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.588  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.298665782 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.588  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.298744115 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.589  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.299214323 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f420888
>>>>> 05-19 20:44:06.589  13110-13110/com.centricular.androidlaunch
>>>>> W/GStreamer+amc﹕ 0:00:00.299291615 0xa140dda0
>>>>> gstamc.c:3886:gst_amc_codec_info_to_caps Unknown color format 0x7f000789
>>>>> 05-19 20:44:06.976  13110-13110/com.centricular.androidlaunch
>>>>> I/GStreamer﹕ GStreamer initialization complete
>>>>> 05-19 20:44:06.976  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ java.io.FileNotFoundException: fontconfig/fonts.conf
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.content.res.AssetManager.openAsset(Native Method)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.content.res.AssetManager.open(AssetManager.java:313)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.content.res.AssetManager.open(AssetManager.java:287)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> org.freedesktop.gstreamer.GStreamer.copyFile(GStreamer.java:69)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> org.freedesktop.gstreamer.GStreamer.copyFonts(GStreamer.java:32)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at org.freedesktop.gstreamer.GStreamer.init(GStreamer.java:17)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.centricular.androidlaunch.AndroidLaunch.onCreate(AndroidLaunch.java:76)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5990)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.access$800(ActivityThread.java:151)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>>>>> 05-19 20:44:06.977  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
>>>>> 05-19 20:44:06.978  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
>>>>> 05-19 20:44:06.979  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
>>>>> 05-19 20:44:06.979  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
>>>>> 05-19 20:44:06.979  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
>>>>> 05-19 20:44:06.979  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>>>>> 05-19 20:44:06.979  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ java.io.FileNotFoundException: ssl/certs/ca-certificates.crt
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.content.res.AssetManager.openAsset(Native Method)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.content.res.AssetManager.open(AssetManager.java:313)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.content.res.AssetManager.open(AssetManager.java:287)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> org.freedesktop.gstreamer.GStreamer.copyFile(GStreamer.java:69)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> org.freedesktop.gstreamer.GStreamer.copyCaCertificates(GStreamer.java:54)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at org.freedesktop.gstreamer.GStreamer.init(GStreamer.java:18)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.centricular.androidlaunch.AndroidLaunch.onCreate(AndroidLaunch.java:76)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5990)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread.access$800(ActivityThread.java:151)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5254)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>>>>> 05-19 20:44:06.980  13110-13110/com.centricular.androidlaunch
>>>>> W/System.err﹕ at
>>>>> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>>>>> 05-19 20:44:07.024  13110-13139/com.centricular.androidlaunch
>>>>> D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
>>>>>
>>>>>
>>>>> I suggest to start project from Gstreamer tutorial, in this case we
>>>>> will be able to focus on rtsp issues and after we will be able to cusomize
>>>>> UI.
>>>>> What do you think?
>>>>>
>>>>> 2015-05-19 20:10 GMT+03:00 Marco Herbst <marco@evercam.io>:
>>>>>>
>>>>>> Dmitry / Liuting,
>>>>>>
>>>>>> Should we move this conversation to github issues?
>>>>>>
>>>>>> It seems like you're exchanging somewhat interesting information and
>>>>>> it is, after all, an open source project and this discussion could be of
>>>>>> interest to other future Android / Gstreamer developers?
>>>>>>
>>>>>> If you agree, Liuting, would you organise that please?
>>>>>>
>>>>>> Dmitry, there probably will be no answer this evening from Liuting as
>>>>>> she has just gone home for the end of the day, but many thanks for keeping
>>>>>> going on this, I'm realy excited to see where we get to.
>>>>>>
>>>>>> Marco
>>>>>>
>>>>>> On 19 May 2015 at 17:59, Dmitry Adjiev <adjiev.dmitry@gmail.com>
>>>>>> wrote:
>>>>>>>
>>>>>>> Hello Liuting, your app doesn't work on my device, here is output:
>>>>>>>
>>>>>>> W/linker  (19181): libgstreamer_android.so has text relocations. This
>>>>>>> is wasting memory and prevents security hardening. Please fix.
>>>>>>> W/VideoCapabilities(19181): Unrecognized profile 2130706433 for
>>>>>>> video/avc
>>>>>>> I/VideoCapabilities(19181): Unsupported profile 4 for video/mp4v-es
>>>>>>> W/VideoCapabilities(19181): Unrecognized profile 2130706433 for
>>>>>>> video/avc
>>>>>>> I/VideoCapabilities(19181): Unsupported profile 4 for video/mp4v-es
>>>>>>> I/GStreamer(19181): GStreamer initialization complete
>>>>>>> D/OpenGLRenderer(19181): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
>>>>>>> D/Atlas   (19181): Validating map...
>>>>>>>
>>>>>>> I'll try to fix it
>>>>>>>
>>>>>>>
>>>>>>> 2015-05-19 15:19 GMT+03:00 Liuting Du <liuting@evercam.io>:
>>>>>>>>
>>>>>>>> Hi Dmitry,
>>>>>>>>
>>>>>>>> Marco means transcode the stream on Evercam server side, not on
>>>>>>>> Android :)
>>>>>>>>
>>>>>>>> I've just built GStreamer for iOS with cerbero for arm64 support, we
>>>>>>>> can build it for Android as well if we really need the feature that
>>>>>>>> it
>>>>>>>> doesn't have in the official release. It seems they are going to
>>>>>>>> release a new version very soon!
>>>>>>>>
>>>>>>>> Thanks!
>>>>>>>> Liuting
>>>>>>>>
>>>>>>>> On Tue, May 19, 2015 at 12:29 PM, Dmitry Adjiev
>>>>>>>> <adjiev.dmitry@gmail.com> wrote:
>>>>>>>> > Transcoding via android device is bad idea IMHO, a year ago I
>>>>>>>> > could not to
>>>>>>>> > build gstreamer omx plugins (hw acceleration h264), but may be in
>>>>>>>> > gstreamer
>>>>>>>> > 1.4.5 it's fixed, I'll check it.
>>>>>>>> > But anyway, it depends from CPU etc etc, I'm sure even good
>>>>>>>> > android device
>>>>>>>> > will not be able to faster encode video with high resolution.
>>>>>>>> > If standard release doesn't support it we can try to build it, for
>>>>>>>> > example
>>>>>>>> > via cerbero ...
>>>>>>>> >
>>>>>>>> > http://docs.gstreamer.com/display/GstSDK/Building+from+source+using+Cerbero
>>>>>>>>

**Comment by liutingdu** [comment]
### Dimtry said:

```
priv->pipeline = gst_parse_launch ("playbin", error);
g_signal_connect (priv->pipeline, "source-setup", G_CALLBACK (need_data_cb), streamer);
```

It uses playbin too, but playbin internally uses rtspsrc, we need to build this and test before

**Comment by liutingdu** [comment]
Created playbin/rtsp problem as a new issue: https://github.com/evercam/evercam-play-android/issues/7
