### ISSUE TITLE
java.lang.NoSuchMethodError: No static method decodeBase64

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-play-android#79]
This error happens with testing snapshot:

```
aused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
9	at io.evercam.Snapshot.getDataFrom(Snapshot.java:438)
10	at io.evercam.Snapshot.getData(Snapshot.java:488)
11	at io.evercam.androidapp.tasks.TestSnapshotTask.doInBackground(TestSnapshotTask.java:74)
12	at io.evercam.androidapp.tasks.TestSnapshotTask.doInBackground(TestSnapshotTask.java:24)
13	at android.os.AsyncTask$2.call(AsyncTask.java:288)
14	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
15	... 3 more
```

**Comment by liutingdu** [comment]
The Apache codec package was relocated in Java wrapper(https://github.com/evercam/evercam.java/blob/master/pom.xml) to avoid this error.

But now it's happening again after upgrading:
```
org.apache.httpcomponents from 4.3.3 to 4.5 
```
or
```
org.apache.httpcomponents from 4.0.1 to 4.1
```
They are now downgraded to fix this.
